### ISSUE TITLE
where is codes? I mean in the blog it mentioned there will be keynotes slides videos and codes

### ISSUE THREAD

**Issue by daqulazhang** [text-machine-lab/ciss2_materials#1]
hello, I have read article here:
https://medium.com/deeppavlov/building-a-knowledge-graph-based-dialogue-system-at-the-2nd-convai-summer-school-ec2d0aa060e5
I'm interested in deeppavlov also, want to warm up with codes but didnt find it here.

**Comment by Mushahid2521** [comment]
I am also looking for the code as it mentioned in the Blog post.
